### ISSUE TITLE
Cant set up an opponent without refering the manager into poty

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#40] opened 2018-11-15 21:42 UTC
selecting a new team....there is no way of proceeding without referring that manager....

**Comment by juur** [comment] 2018-11-16 19:56
I can't reproduce this. I can invite other Clubs by just provide Club/City/Team name.
Did Google Chrome try to autofill the name or something of the referring manager with your name? If you fill in any single box in that section, it makes you fill them all in ....

**Comment by juur** [comment] 2018-12-07 18:48
Closing as I guess it's OK now.

**Closed** 2018-12-07 18:48 UTC
Labels: bug, question
